### ISSUE TITLE
`qiskit_to_tk` does not work with exponentials in parameterized circuits

### ISSUE THREAD

**Issue by ruihao-li** [CQCL/pytket-qiskit#185] opened 2023-10-08 15:56 UTC
Here is a minimal example in which I ran into error:

```python
from qiskit import QuantumCircuit
from qiskit.circuit import Parameter
from pytket.extensions.qiskit import qiskit_to_tk

K = Parameter("K")
kappa = K.exp()
qc = QuantumCircuit(1)
qc.rz(kappa, 0)

tk_backend = IBMQBackend("ibm_nairobi")
tk_qc = qiskit_to_tk(qc)
```
The error message I got was:
```
RuntimeError: Unable to convert sympy expression exp(K)
```
I tested with other functions such as `arccos()`, `log()`, and so on and they all worked. It seems it is only the exponential that is giving the problem.
Is there a workaround for this? Thanks!

qiskit version: 0.44.2
pytket-qiskit version: 0.44.0

**Comment by CalMacCQ** [comment] 2023-10-09 07:38
Thank you for making an issue. This is definetly a bug and something we should fix soon. 

I can't immediately think of a workaround but if I do then I'll share it here.

**Comment by ruihao-li** [comment] 2023-10-09 13:28
Thank you! Look forward to the fix!

**Comment by CalMacCQ** [comment] 2023-10-10 10:37
Turns out this was caused by an issue with the bindings in tket itself. See the [tket issue](https://github.com/CQCL/tket/issues/1068).

Fortunately this is now fixed in https://github.com/CQCL/tket/pull/1069.

The fix should be in the next pytket release (coming soon) and the pytket-qiskit release is due shortly after.

Thanks again for rasing the issue.

**Closed** 2023-10-10 13:41 UTC
Labels: bug
